name: Test asset upload

on: push

jobs:
  main_job:
    name: Main Job
    runs-on: windows-latest
    env:
      ZIP_NAME: abimo_latest_win64.zip
    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
      - name: Fake the result of a build process
        run: |
          mkdir release
          echo "build result" > release/windows-release.txt
        shell: cmd
      - name: Rename release directory
        run: rename release abimo_win64
        shell: cmd
      - name: Update Windows-related asset in latest release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest-1
          files: abimo_win64
