name: Test asset upload

on: push

jobs:
  windows:
    runs-on: windows-latest
    env:
      ZIP_NAME: abimo_latest_windows.zip
    steps:
      - name: Fake the result of a build process
        shell: cmd
        run: |
          mkdir release
          echo "build result" > release/windows-release.txt
      - name: Create zip-file
        shell: pwsh
        run: Compress-Archive -Path release/* -DestinationPath ${{ env.ZIP_NAME }}
      - name: List files
        shell: cmd
        run: dir /s /b
      - name: Update Windows-related asset in latest release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest-1
          files: ${{ env.ZIP_NAME }}
  linux:
    runs-on: linux-latest
    env:
      ZIP_NAME: abimo_latest_linux.tar.gz
    steps:
      - name: Fake the result of a build process
        run: |
          mkdir release
          echo "build result" > release/linux-release.txt
      - name: Create archive
        run: tar -czvf ${{ env.ZIP_NAME }} release/*
      - name: List files
        run: ls -l
      - name: Update Linux-related asset in latest release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest-1
          files: ${{ env.ZIP_NAME }}

  mac:
    runs-on: macos-latest
    env:
      ZIP_NAME: abimo_latest_macos.tar.gz
    steps:
      - name: Fake the result of a build process
        run: |
          mkdir release
          echo "build result" > release/macos-release.txt
      - name: Create archive
        run: tar -czvf ${{ env.ZIP_NAME }} release/*
      - name: List files
        run: ls -l
      - name: Update MacOS-related asset in latest release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest-1
          files: ${{ env.ZIP_NAME }}
